static_sites:
  - name: crop-intelligence-frontend
    node:
      version: 18.x
    buildCommand: |
      cd /opt/render/project/src/frontend
      npm run build:ci
    publicPath: /dist
    envVars:
      - key: VITE_API_URL
        value: https://crop-intelligence-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
