services:
  # Backend Service
  - type: web
    name: crop-intelligence-backend
    env: node
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      echo "Installing backend dependencies..."
      cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    node:
      version: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: crop-intelligence-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: "30"
      - key: UPLOAD_DIR
        value: /tmp/uploads
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
      ignorePaths:
        - frontend/**
        - node_modules/**
        - .git/**

  # Frontend Service
  - type: web
    name: crop-intelligence-frontend
    env: static
    region: oregon  # Same as backend for best performance
    buildCommand: |
      echo "Installing frontend dependencies..."
      cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://crop-intelligence-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - path: /*
        destination: /index.html
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
      ignorePaths:
        - backend/**
        - node_modules/**
        - .git/**

databases:
  - name: crop-intelligence-db
    databaseName: cropintelligence
    user: cropinteluser
    plan: free
    version: 6.0

# Global settings
global:
  nodeVersion: 18.x
  buildCommand: echo "Global build command"
  autoDeploy: true
