services:
  # Backend Service
  - type: web
    name: crop-intelligence-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: crop-intelligence-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: "30"
      - key: UPLOAD_DIR
        value: /tmp/uploads
    healthCheckPath: /api/health
    plan: free

  # Frontend Service
  - type: web
    name: crop-intelligence-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://crop-intelligence-backend.onrender.com
    routes:
      - path: /*
        destination: /index.html
    plan: free
    autoDeploy: true

databases:
  - name: crop-intelligence-db
    databaseName: cropintelligence
    user: cropinteluser
    plan: free
    version: 6.0
