services:
  # Backend Service
  - type: web
    name: crop-intelligence-backend
    env: node
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      echo "Installing backend dependencies..."
      cd backend
      export NODE_ENV=production
      npm ci --only=production
    startCommand: cd backend && npm start
    node:
      version: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # For MongoDB Atlas (uncomment and replace with your actual connection string)
      - key: MONGODB_URI
        sync: false
        value: ${MONGODB_URI}
      # For Render's built-in database (uncomment if using Render's database)
      # - key: MONGODB_URI
      #   fromDatabase:
      #     name: crop-intelligence-db
      #     property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: "30"
      - key: UPLOAD_DIR
        value: /tmp/uploads
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
      ignorePaths:
        - frontend/**
        - node_modules/**
        - .git/**

  # Frontend Service
  - type: web
    name: crop-intelligence-frontend
    env: static
    region: oregon  # Same as backend for best performance
    buildCommand: |
      echo "=== Starting Frontend Build ==="
      cd frontend
      
      echo "1. Cleaning up..."
      rm -rf node_modules
      rm -f package-lock.json
      
      echo "2. Installing Node.js version manager..."
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      
      echo "3. Installing Node.js 18..."
      nvm install 18
      nvm use 18
      
      echo "4. Installing dependencies..."
      npm install -g npm@latest
      npm install --legacy-peer-deps
      
      echo "5. Building application..."
      npm run build
      
      echo "6. Verifying build..."
      ls -la dist/
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://crop-intelligence-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - path: /*
        destination: /index.html
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
      ignorePaths:
        - backend/**
        - node_modules/**
        - .git/**

databases:
  - name: crop-intelligence-db
    databaseName: cropintelligence
    user: cropinteluser
    plan: free
    version: 6.0

# Global settings
global:
  nodeVersion: 18.x
  buildCommand: echo "Global build command"
  autoDeploy: true
