services:
  - type: web
    name: crop-intelligence-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: crop-intelligence-db
          property: connectionString
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
